version: '3'
services:
  smartcities-app:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: smartcities-db
      DATABASE_PORT: 3306
      DATABASE_NAME: smartcitiesdb
      DATABASE_USERNAME: smartcities
      DATABASE_PASSWORD: my-secret
      DATABASE_SSL: 'false'
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    links:
      - smartcities-db

  smartcities-db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - smartcities-data:/var/lib/mysql
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: smartcitiesdb
      MYSQL_USER: smartcities
      MYSQL_PASSWORD: my-secret

volumes:
  smartcities-data:
