insert into cities(province_id, name, id ) values (1, "Leticia", 1);
insert into cities(province_id, name, id ) values (1, "El Encanto", 2);
insert into cities(province_id, name, id ) values (1, "La Chorrera", 3);
insert into cities(province_id, name, id ) values (1, "La Pedrera", 4);
insert into cities(province_id, name, id ) values (1, "La Victoria", 5);
insert into cities(province_id, name, id ) values (1, "Puerto Arica", 6);
insert into cities(province_id, name, id ) values (1, "Puerto Nariño", 7);
insert into cities(province_id, name, id ) values (1, "Puerto Santander", 8);
insert into cities(province_id, name, id ) values (1, "Tarapacá", 9);
insert into cities(province_id, name, id ) values (1, "Puerto Alegría", 10);
insert into cities(province_id, name, id ) values (1, "Miriti Paraná", 11);
insert into cities(province_id, name, id ) values (2, "Medellín", 12);
insert into cities(province_id, name, id ) values (2, "Abejorral", 13);
insert into cities(province_id, name, id ) values (2, "Abriaquí", 14);
insert into cities(province_id, name, id ) values (2, "Alejandría", 15);
insert into cities(province_id, name, id ) values (2, "Amagá", 16);
insert into cities(province_id, name, id ) values (2, "Amalfi", 17);
insert into cities(province_id, name, id ) values (2, "Andes", 18);
insert into cities(province_id, name, id ) values (2, "Angelópolis", 19);
insert into cities(province_id, name, id ) values (2, "Angostura", 20);
insert into cities(province_id, name, id ) values (2, "Anorí", 21);
insert into cities(province_id, name, id ) values (2, "Anza", 22);
insert into cities(province_id, name, id ) values (2, "Apartadó", 23);
insert into cities(province_id, name, id ) values (2, "Arboletes", 24);
insert into cities(province_id, name, id ) values (2, "Argelia", 25);
insert into cities(province_id, name, id ) values (2, "Armenia", 26);
insert into cities(province_id, name, id ) values (2, "Barbosa", 27);
insert into cities(province_id, name, id ) values (2, "Bello", 28);
insert into cities(province_id, name, id ) values (2, "Betania", 29);
insert into cities(province_id, name, id ) values (2, "Betulia", 30);
insert into cities(province_id, name, id ) values (2, "Ciudad Bolívar", 31);
insert into cities(province_id, name, id ) values (2, "Briceño", 32);
insert into cities(province_id, name, id ) values (2, "Buriticá", 33);
insert into cities(province_id, name, id ) values (2, "Cáceres", 34);
insert into cities(province_id, name, id ) values (2, "Caicedo", 35);
insert into cities(province_id, name, id ) values (2, "Caldas", 36);
insert into cities(province_id, name, id ) values (2, "Campamento", 37);
insert into cities(province_id, name, id ) values (2, "Cañasgordas", 38);
insert into cities(province_id, name, id ) values (2, "Caracolí", 39);
insert into cities(province_id, name, id ) values (2, "Caramanta", 40);
insert into cities(province_id, name, id ) values (2, "Carepa", 41);
insert into cities(province_id, name, id ) values (2, "Carolina", 42);
insert into cities(province_id, name, id ) values (2, "Caucasia", 43);
insert into cities(province_id, name, id ) values (2, "Chigorodó", 44);
insert into cities(province_id, name, id ) values (2, "Cisneros", 45);
insert into cities(province_id, name, id ) values (2, "Cocorná", 46);
insert into cities(province_id, name, id ) values (2, "Concepción", 47);
insert into cities(province_id, name, id ) values (2, "Concordia", 48);
insert into cities(province_id, name, id ) values (2, "Copacabana", 49);
insert into cities(province_id, name, id ) values (2, "Dabeiba", 50);
insert into cities(province_id, name, id ) values (2, "Don Matías", 51);
insert into cities(province_id, name, id ) values (2, "Ebéjico", 52);
insert into cities(province_id, name, id ) values (2, "El Bagre", 53);
insert into cities(province_id, name, id ) values (2, "Entrerrios", 54);
insert into cities(province_id, name, id ) values (2, "Envigado", 55);
insert into cities(province_id, name, id ) values (2, "Fredonia", 56);
insert into cities(province_id, name, id ) values (2, "Giraldo", 57);
insert into cities(province_id, name, id ) values (2, "Girardota", 58);
insert into cities(province_id, name, id ) values (2, "Gómez Plata", 59);
insert into cities(province_id, name, id ) values (2, "Guadalupe", 60);
insert into cities(province_id, name, id ) values (2, "Guarne", 61);
insert into cities(province_id, name, id ) values (2, "Guatapé", 62);
insert into cities(province_id, name, id ) values (2, "Heliconia", 63);
insert into cities(province_id, name, id ) values (2, "Hispania", 64);
insert into cities(province_id, name, id ) values (2, "Itagui", 65);
insert into cities(province_id, name, id ) values (2, "Ituango", 66);
insert into cities(province_id, name, id ) values (2, "Belmira", 67);
insert into cities(province_id, name, id ) values (2, "Jericó", 68);
insert into cities(province_id, name, id ) values (2, "La Ceja", 69);
insert into cities(province_id, name, id ) values (2, "La Estrella", 70);
insert into cities(province_id, name, id ) values (2, "La Pintada", 71);
insert into cities(province_id, name, id ) values (2, "La Unión", 72);
insert into cities(province_id, name, id ) values (2, "Liborina", 73);
insert into cities(province_id, name, id ) values (2, "Maceo", 74);
insert into cities(province_id, name, id ) values (2, "Marinilla", 75);
insert into cities(province_id, name, id ) values (2, "Montebello", 76);
insert into cities(province_id, name, id ) values (2, "Murindó", 77);
insert into cities(province_id, name, id ) values (2, "Mutatá", 78);
insert into cities(province_id, name, id ) values (2, "Nariño", 79);
insert into cities(province_id, name, id ) values (2, "Necoclí", 80);
insert into cities(province_id, name, id ) values (2, "Nechí", 81);
insert into cities(province_id, name, id ) values (2, "Olaya", 82);
insert into cities(province_id, name, id ) values (2, "Peñol", 83);
insert into cities(province_id, name, id ) values (2, "Peque", 84);
insert into cities(province_id, name, id ) values (2, "Pueblorrico", 85);
insert into cities(province_id, name, id ) values (2, "Puerto Berrío", 86);
insert into cities(province_id, name, id ) values (2, "Puerto Nare", 87);
insert into cities(province_id, name, id ) values (2, "Puerto Triunfo", 88);
insert into cities(province_id, name, id ) values (2, "Remedios", 89);
insert into cities(province_id, name, id ) values (2, "Retiro", 90);
insert into cities(province_id, name, id ) values (2, "Rionegro", 91);
insert into cities(province_id, name, id ) values (2, "Sabanalarga", 92);
insert into cities(province_id, name, id ) values (2, "Sabaneta", 93);
insert into cities(province_id, name, id ) values (2, "Salgar", 94);
insert into cities(province_id, name, id ) values (2, "San Francisco", 95);
insert into cities(province_id, name, id ) values (2, "San Jerónimo", 96);
insert into cities(province_id, name, id ) values (2, "San Luis", 97);
insert into cities(province_id, name, id ) values (2, "San Pedro", 98);
insert into cities(province_id, name, id ) values (2, "San Rafael", 99);
insert into cities(province_id, name, id ) values (2, "San Roque", 100);
insert into cities(province_id, name, id ) values (2, "San Vicente", 101);
insert into cities(province_id, name, id ) values (2, "Santa Bárbara", 102);
insert into cities(province_id, name, id ) values (2, "Santo Domingo", 103);
insert into cities(province_id, name, id ) values (2, "El Santuario", 104);
insert into cities(province_id, name, id ) values (2, "Segovia", 105);
insert into cities(province_id, name, id ) values (2, "Sopetrán", 106);
insert into cities(province_id, name, id ) values (2, "Támesis", 107);
insert into cities(province_id, name, id ) values (2, "Tarazá", 108);
insert into cities(province_id, name, id ) values (2, "Tarso", 109);
insert into cities(province_id, name, id ) values (2, "Titiribí", 110);
insert into cities(province_id, name, id ) values (2, "Toledo", 111);
insert into cities(province_id, name, id ) values (2, "Turbo", 112);
insert into cities(province_id, name, id ) values (2, "Uramita", 113);
insert into cities(province_id, name, id ) values (2, "Urrao", 114);
insert into cities(province_id, name, id ) values (2, "Valdivia", 115);
insert into cities(province_id, name, id ) values (2, "Valparaíso", 116);
insert into cities(province_id, name, id ) values (2, "Vegachí", 117);
insert into cities(province_id, name, id ) values (2, "Venecia", 118);
insert into cities(province_id, name, id ) values (2, "Yalí", 119);
insert into cities(province_id, name, id ) values (2, "Yarumal", 120);
insert into cities(province_id, name, id ) values (2, "Yolombó", 121);
insert into cities(province_id, name, id ) values (2, "Yondó", 122);
insert into cities(province_id, name, id ) values (2, "Zaragoza", 123);
insert into cities(province_id, name, id ) values (2, "San Pedro de Uraba", 124);
insert into cities(province_id, name, id ) values (2, "Santafé de Antioquia", 125);
insert into cities(province_id, name, id ) values (2, "Santa Rosa de Osos", 126);
insert into cities(province_id, name, id ) values (2, "San Andrés de Cuerquía", 127);
insert into cities(province_id, name, id ) values (2, "Vigía del Fuerte", 128);
insert into cities(province_id, name, id ) values (2, "San José de La Montaña", 129);
insert into cities(province_id, name, id ) values (2, "San Juan de Urabá", 130);
insert into cities(province_id, name, id ) values (2, "El Carmen de Viboral", 131);
insert into cities(province_id, name, id ) values (2, "San Carlos", 132);
insert into cities(province_id, name, id ) values (2, "Frontino", 133);
insert into cities(province_id, name, id ) values (2, "Granada", 134);
insert into cities(province_id, name, id ) values (2, "Jardín", 135);
insert into cities(province_id, name, id ) values (2, "Sonsón", 136);
insert into cities(province_id, name, id ) values (3, "Arauquita", 137);
insert into cities(province_id, name, id ) values (3, "Cravo Norte", 138);
insert into cities(province_id, name, id ) values (3, "Fortul", 139);
insert into cities(province_id, name, id ) values (3, "Puerto Rondón", 140);
insert into cities(province_id, name, id ) values (3, "Saravena", 141);
insert into cities(province_id, name, id ) values (3, "Tame", 142);
insert into cities(province_id, name, id ) values (3, "Arauca", 143);
insert into cities(province_id, name, id ) values (4, "Providencia", 144);
insert into cities(province_id, name, id ) values (4, "San Andrés", 145);
insert into cities(province_id, name, id ) values (5, "Barranquilla", 146);
insert into cities(province_id, name, id ) values (5, "Baranoa", 147);
insert into cities(province_id, name, id ) values (5, "Candelaria", 148);
insert into cities(province_id, name, id ) values (5, "Galapa", 149);
insert into cities(province_id, name, id ) values (5, "Luruaco", 150);
insert into cities(province_id, name, id ) values (5, "Malambo", 151);
insert into cities(province_id, name, id ) values (5, "Manatí", 152);
insert into cities(province_id, name, id ) values (5, "Piojó", 153);
insert into cities(province_id, name, id ) values (5, "Polonuevo", 154);
insert into cities(province_id, name, id ) values (5, "Sabanagrande", 155);
insert into cities(province_id, name, id ) values (5, "Sabanalarga", 156);
insert into cities(province_id, name, id ) values (5, "Santa Lucía", 157);
insert into cities(province_id, name, id ) values (5, "Santo Tomás", 158);
insert into cities(province_id, name, id ) values (5, "Soledad", 159);
insert into cities(province_id, name, id ) values (5, "Suan", 160);
insert into cities(province_id, name, id ) values (5, "Tubará", 161);
insert into cities(province_id, name, id ) values (5, "Usiacurí", 162);
insert into cities(province_id, name, id ) values (5, "Juan de Acosta", 163);
insert into cities(province_id, name, id ) values (5, "Palmar de Varela", 164);
insert into cities(province_id, name, id ) values (5, "Campo de La Cruz", 165);
insert into cities(province_id, name, id ) values (5, "Repelón", 166);
insert into cities(province_id, name, id ) values (5, "Puerto Colombia", 167);
insert into cities(province_id, name, id ) values (5, "Ponedera", 168);
insert into cities(province_id, name, id ) values (6, "Achí", 169);
insert into cities(province_id, name, id ) values (6, "Arenal", 170);
insert into cities(province_id, name, id ) values (6, "Arjona", 171);
insert into cities(province_id, name, id ) values (6, "Arroyohondo", 172);
insert into cities(province_id, name, id ) values (6, "Calamar", 173);
insert into cities(province_id, name, id ) values (6, "Cantagallo", 174);
insert into cities(province_id, name, id ) values (6, "Cicuco", 175);
insert into cities(province_id, name, id ) values (6, "Córdoba", 176);
insert into cities(province_id, name, id ) values (6, "Clemencia", 177);
insert into cities(province_id, name, id ) values (6, "El Guamo", 178);
insert into cities(province_id, name, id ) values (6, "Magangué", 179);
insert into cities(province_id, name, id ) values (6, "Mahates", 180);
insert into cities(province_id, name, id ) values (6, "Margarita", 181);
insert into cities(province_id, name, id ) values (6, "Montecristo", 182);
insert into cities(province_id, name, id ) values (6, "Mompós", 183);
insert into cities(province_id, name, id ) values (6, "Morales", 184);
insert into cities(province_id, name, id ) values (6, "Norosí", 185);
insert into cities(province_id, name, id ) values (6, "Pinillos", 186);
insert into cities(province_id, name, id ) values (6, "Regidor", 187);
insert into cities(province_id, name, id ) values (6, "Río Viejo", 188);
insert into cities(province_id, name, id ) values (6, "San Estanislao", 189);
insert into cities(province_id, name, id ) values (6, "San Fernando", 190);
insert into cities(province_id, name, id ) values (6, "San Juan Nepomuceno", 191);
insert into cities(province_id, name, id ) values (6, "Santa Catalina", 192);
insert into cities(province_id, name, id ) values (6, "Santa Rosa", 193);
insert into cities(province_id, name, id ) values (6, "Simití", 194);
insert into cities(province_id, name, id ) values (6, "Soplaviento", 195);
insert into cities(province_id, name, id ) values (6, "Talaigua Nuevo", 196);
insert into cities(province_id, name, id ) values (6, "Tiquisio", 197);
insert into cities(province_id, name, id ) values (6, "Turbaco", 198);
insert into cities(province_id, name, id ) values (6, "Turbaná", 199);
insert into cities(province_id, name, id ) values (6, "Villanueva", 200);
insert into cities(province_id, name, id ) values (6, "Barranco de Loba", 201);
insert into cities(province_id, name, id ) values (6, "Santa Rosa del Sur", 202);
insert into cities(province_id, name, id ) values (6, "Hatillo de Loba", 203);
insert into cities(province_id, name, id ) values (6, "El Carmen de Bolívar", 204);
insert into cities(province_id, name, id ) values (6, "San Martín de Loba", 205);
insert into cities(province_id, name, id ) values (6, "Altos del Rosario", 206);
insert into cities(province_id, name, id ) values (6, "San Jacinto del Cauca", 207);
insert into cities(province_id, name, id ) values (6, "San Pablo de Borbur", 208);
insert into cities(province_id, name, id ) values (6, "San Jacinto", 209);
insert into cities(province_id, name, id ) values (6, "El Peñón", 210);
insert into cities(province_id, name, id ) values (6, "Cartagena", 211);
insert into cities(province_id, name, id ) values (6, "María la Baja", 212);
insert into cities(province_id, name, id ) values (6, "San Cristóbal", 213);
insert into cities(province_id, name, id ) values (6, "Zambrano", 214);
insert into cities(province_id, name, id ) values (7, "Tununguá", 215);
insert into cities(province_id, name, id ) values (7, "Motavita", 216);
insert into cities(province_id, name, id ) values (7, "Ciénega", 217);
insert into cities(province_id, name, id ) values (7, "Tunja", 218);
insert into cities(province_id, name, id ) values (7, "Almeida", 219);
insert into cities(province_id, name, id ) values (7, "Aquitania", 220);
insert into cities(province_id, name, id ) values (7, "Arcabuco", 221);
insert into cities(province_id, name, id ) values (7, "Berbeo", 222);
insert into cities(province_id, name, id ) values (7, "Betéitiva", 223);
insert into cities(province_id, name, id ) values (7, "Boavita", 224);
insert into cities(province_id, name, id ) values (7, "Boyacá", 225);
insert into cities(province_id, name, id ) values (7, "Briceño", 226);
insert into cities(province_id, name, id ) values (7, "Buena Vista", 227);
insert into cities(province_id, name, id ) values (7, "Busbanzá", 228);
insert into cities(province_id, name, id ) values (7, "Caldas", 229);
insert into cities(province_id, name, id ) values (7, "Campohermoso", 230);
insert into cities(province_id, name, id ) values (7, "Cerinza", 231);
insert into cities(province_id, name, id ) values (7, "Chinavita", 232);
insert into cities(province_id, name, id ) values (7, "Chiquinquirá", 233);
insert into cities(province_id, name, id ) values (7, "Chiscas", 234);
insert into cities(province_id, name, id ) values (7, "Chita", 235);
insert into cities(province_id, name, id ) values (7, "Chitaraque", 236);
insert into cities(province_id, name, id ) values (7, "Chivatá", 237);
insert into cities(province_id, name, id ) values (7, "Cómbita", 238);
insert into cities(province_id, name, id ) values (7, "Coper", 239);
insert into cities(province_id, name, id ) values (7, "Corrales", 240);
insert into cities(province_id, name, id ) values (7, "Covarachía", 241);
insert into cities(province_id, name, id ) values (7, "Cubará", 242);
insert into cities(province_id, name, id ) values (7, "Cucaita", 243);
insert into cities(province_id, name, id ) values (7, "Cuítiva", 244);
insert into cities(province_id, name, id ) values (7, "Chíquiza", 245);
insert into cities(province_id, name, id ) values (7, "Chivor", 246);
insert into cities(province_id, name, id ) values (7, "Duitama", 247);
insert into cities(province_id, name, id ) values (7, "El Cocuy", 248);
insert into cities(province_id, name, id ) values (7, "El Espino", 249);
insert into cities(province_id, name, id ) values (7, "Firavitoba", 250);
insert into cities(province_id, name, id ) values (7, "Floresta", 251);
insert into cities(province_id, name, id ) values (7, "Gachantivá", 252);
insert into cities(province_id, name, id ) values (7, "Gameza", 253);
insert into cities(province_id, name, id ) values (7, "Garagoa", 254);
insert into cities(province_id, name, id ) values (7, "Guacamayas", 255);
insert into cities(province_id, name, id ) values (7, "Guateque", 256);
insert into cities(province_id, name, id ) values (7, "Guayatá", 257);
insert into cities(province_id, name, id ) values (7, "Güicán", 258);
insert into cities(province_id, name, id ) values (7, "Iza", 259);
insert into cities(province_id, name, id ) values (7, "Jenesano", 260);
insert into cities(province_id, name, id ) values (7, "Jericó", 261);
insert into cities(province_id, name, id ) values (7, "Labranzagrande", 262);
insert into cities(province_id, name, id ) values (7, "La Capilla", 263);
insert into cities(province_id, name, id ) values (7, "La Victoria", 264);
insert into cities(province_id, name, id ) values (7, "Macanal", 265);
insert into cities(province_id, name, id ) values (7, "Maripí", 266);
insert into cities(province_id, name, id ) values (7, "Miraflores", 267);
insert into cities(province_id, name, id ) values (7, "Mongua", 268);
insert into cities(province_id, name, id ) values (7, "Monguí", 269);
insert into cities(province_id, name, id ) values (7, "Moniquirá", 270);
insert into cities(province_id, name, id ) values (7, "Muzo", 271);
insert into cities(province_id, name, id ) values (7, "Nobsa", 272);
insert into cities(province_id, name, id ) values (7, "Nuevo Colón", 273);
insert into cities(province_id, name, id ) values (7, "Oicatá", 274);
insert into cities(province_id, name, id ) values (7, "Otanche", 275);
insert into cities(province_id, name, id ) values (7, "Pachavita", 276);
insert into cities(province_id, name, id ) values (7, "Páez", 277);
insert into cities(province_id, name, id ) values (7, "Paipa", 278);
insert into cities(province_id, name, id ) values (7, "Pajarito", 279);
insert into cities(province_id, name, id ) values (7, "Panqueba", 280);
insert into cities(province_id, name, id ) values (7, "Pauna", 281);
insert into cities(province_id, name, id ) values (7, "Paya", 282);
insert into cities(province_id, name, id ) values (7, "Pesca", 283);
insert into cities(province_id, name, id ) values (7, "Pisba", 284);
insert into cities(province_id, name, id ) values (7, "Puerto Boyacá", 285);
insert into cities(province_id, name, id ) values (7, "Quípama", 286);
insert into cities(province_id, name, id ) values (7, "Ramiriquí", 287);
insert into cities(province_id, name, id ) values (7, "Ráquira", 288);
insert into cities(province_id, name, id ) values (7, "Rondón", 289);
insert into cities(province_id, name, id ) values (7, "Saboyá", 290);
insert into cities(province_id, name, id ) values (7, "Sáchica", 291);
insert into cities(province_id, name, id ) values (7, "Samacá", 292);
insert into cities(province_id, name, id ) values (7, "San Eduardo", 293);
insert into cities(province_id, name, id ) values (7, "San Mateo", 294);
insert into cities(province_id, name, id ) values (7, "Santana", 295);
insert into cities(province_id, name, id ) values (7, "Santa María", 296);
insert into cities(province_id, name, id ) values (7, "Santa Sofía", 297);
insert into cities(province_id, name, id ) values (7, "Sativanorte", 298);
insert into cities(province_id, name, id ) values (7, "Sativasur", 299);
insert into cities(province_id, name, id ) values (7, "Siachoque", 300);
insert into cities(province_id, name, id ) values (7, "Soatá", 301);
insert into cities(province_id, name, id ) values (7, "Socotá", 302);
insert into cities(province_id, name, id ) values (7, "Socha", 303);
insert into cities(province_id, name, id ) values (7, "Sogamoso", 304);
insert into cities(province_id, name, id ) values (7, "Somondoco", 305);
insert into cities(province_id, name, id ) values (7, "Sora", 306);
insert into cities(province_id, name, id ) values (7, "Sotaquirá", 307);
insert into cities(province_id, name, id ) values (7, "Soracá", 308);
insert into cities(province_id, name, id ) values (7, "Susacón", 309);
insert into cities(province_id, name, id ) values (7, "Sutamarchán", 310);
insert into cities(province_id, name, id ) values (7, "Sutatenza", 311);
insert into cities(province_id, name, id ) values (7, "Tasco", 312);
insert into cities(province_id, name, id ) values (7, "Tenza", 313);
insert into cities(province_id, name, id ) values (7, "Tibaná", 314);
insert into cities(province_id, name, id ) values (7, "Tinjacá", 315);
insert into cities(province_id, name, id ) values (7, "Tipacoque", 316);
insert into cities(province_id, name, id ) values (7, "Toca", 317);
insert into cities(province_id, name, id ) values (7, "Tópaga", 318);
insert into cities(province_id, name, id ) values (7, "Tota", 319);
insert into cities(province_id, name, id ) values (7, "Turmequé", 320);
insert into cities(province_id, name, id ) values (7, "Tutazá", 321);
insert into cities(province_id, name, id ) values (7, "Umbita", 322);
insert into cities(province_id, name, id ) values (7, "Ventaquemada", 323);
insert into cities(province_id, name, id ) values (7, "Viracachá", 324);
insert into cities(province_id, name, id ) values (7, "Zetaquira", 325);
insert into cities(province_id, name, id ) values (7, "Togüí", 326);
insert into cities(province_id, name, id ) values (7, "Villa de Leyva", 327);
insert into cities(province_id, name, id ) values (7, "Paz de Río", 328);
insert into cities(province_id, name, id ) values (7, "Santa Rosa de Viterbo", 329);
insert into cities(province_id, name, id ) values (7, "San Pablo de Borbur", 330);
insert into cities(province_id, name, id ) values (7, "San Luis de Gaceno", 331);
insert into cities(province_id, name, id ) values (7, "San José de Pare", 332);
insert into cities(province_id, name, id ) values (7, "San Miguel de Sema", 333);
insert into cities(province_id, name, id ) values (7, "Tuta", 334);
insert into cities(province_id, name, id ) values (7, "Tibasosa", 335);
insert into cities(province_id, name, id ) values (7, "La Uvita", 336);
insert into cities(province_id, name, id ) values (7, "Belén", 337);
insert into cities(province_id, name, id ) values (8, "Manizales", 338);
insert into cities(province_id, name, id ) values (8, "Aguadas", 339);
insert into cities(province_id, name, id ) values (8, "Anserma", 340);
insert into cities(province_id, name, id ) values (8, "Aranzazu", 341);
insert into cities(province_id, name, id ) values (8, "Belalcázar", 342);
insert into cities(province_id, name, id ) values (8, "Chinchiná", 343);
insert into cities(province_id, name, id ) values (8, "Filadelfia", 344);
insert into cities(province_id, name, id ) values (8, "La Dorada", 345);
insert into cities(province_id, name, id ) values (8, "La Merced", 346);
insert into cities(province_id, name, id ) values (8, "Manzanares", 347);
insert into cities(province_id, name, id ) values (8, "Marmato", 348);
insert into cities(province_id, name, id ) values (8, "Marulanda", 349);
insert into cities(province_id, name, id ) values (8, "Neira", 350);
insert into cities(province_id, name, id ) values (8, "Norcasia", 351);
insert into cities(province_id, name, id ) values (8, "Pácora", 352);
insert into cities(province_id, name, id ) values (8, "Palestina", 353);
insert into cities(province_id, name, id ) values (8, "Pensilvania", 354);
insert into cities(province_id, name, id ) values (8, "Riosucio", 355);
insert into cities(province_id, name, id ) values (8, "Risaralda", 356);
insert into cities(province_id, name, id ) values (8, "Salamina", 357);
insert into cities(province_id, name, id ) values (8, "Samaná", 358);
insert into cities(province_id, name, id ) values (8, "San José", 359);
insert into cities(province_id, name, id ) values (8, "Supía", 360);
insert into cities(province_id, name, id ) values (8, "Victoria", 361);
insert into cities(province_id, name, id ) values (8, "Villamaría", 362);
insert into cities(province_id, name, id ) values (8, "Viterbo", 363);
insert into cities(province_id, name, id ) values (8, "Marquetalia", 364);
insert into cities(province_id, name, id ) values (9, "Florencia", 365);
insert into cities(province_id, name, id ) values (9, "Albania", 366);
insert into cities(province_id, name, id ) values (9, "Curillo", 367);
insert into cities(province_id, name, id ) values (9, "El Doncello", 368);
insert into cities(province_id, name, id ) values (9, "El Paujil", 369);
insert into cities(province_id, name, id ) values (9, "Morelia", 370);
insert into cities(province_id, name, id ) values (9, "Puerto Rico", 371);
insert into cities(province_id, name, id ) values (9, "Solano", 372);
insert into cities(province_id, name, id ) values (9, "Solita", 373);
insert into cities(province_id, name, id ) values (9, "Valparaíso", 374);
insert into cities(province_id, name, id ) values (9, "San José del Fragua", 375);
insert into cities(province_id, name, id ) values (9, "Belén de Los Andaquies", 376);
insert into cities(province_id, name, id ) values (9, "Cartagena del Chairá", 377);
insert into cities(province_id, name, id ) values (9, "Milán", 378);
insert into cities(province_id, name, id ) values (9, "La Montañita", 379);
insert into cities(province_id, name, id ) values (9, "San Vicente del Caguán", 380);
insert into cities(province_id, name, id ) values (10, "Yopal", 381);
insert into cities(province_id, name, id ) values (10, "Aguazul", 382);
insert into cities(province_id, name, id ) values (10, "Chámeza", 383);
insert into cities(province_id, name, id ) values (10, "Hato Corozal", 384);
insert into cities(province_id, name, id ) values (10, "La Salina", 385);
insert into cities(province_id, name, id ) values (10, "Monterrey", 386);
insert into cities(province_id, name, id ) values (10, "Pore", 387);
insert into cities(province_id, name, id ) values (10, "Recetor", 388);
insert into cities(province_id, name, id ) values (10, "Sabanalarga", 389);
insert into cities(province_id, name, id ) values (10, "Sácama", 390);
insert into cities(province_id, name, id ) values (10, "Tauramena", 391);
insert into cities(province_id, name, id ) values (10, "Trinidad", 392);
insert into cities(province_id, name, id ) values (10, "Villanueva", 393);
insert into cities(province_id, name, id ) values (10, "San Luis de Gaceno", 394);
insert into cities(province_id, name, id ) values (10, "Paz de Ariporo", 395);
insert into cities(province_id, name, id ) values (10, "Nunchía", 396);
insert into cities(province_id, name, id ) values (10, "Maní", 397);
insert into cities(province_id, name, id ) values (10, "Támara", 398);
insert into cities(province_id, name, id ) values (10, "Orocué", 399);
insert into cities(province_id, name, id ) values (11, "Popayán", 400);
insert into cities(province_id, name, id ) values (11, "Almaguer", 401);
insert into cities(province_id, name, id ) values (11, "Argelia", 402);
insert into cities(province_id, name, id ) values (11, "Balboa", 403);
insert into cities(province_id, name, id ) values (11, "Bolívar", 404);
insert into cities(province_id, name, id ) values (11, "Buenos Aires", 405);
insert into cities(province_id, name, id ) values (11, "Cajibío", 406);
insert into cities(province_id, name, id ) values (11, "Caldono", 407);
insert into cities(province_id, name, id ) values (11, "Caloto", 408);
insert into cities(province_id, name, id ) values (11, "Corinto", 409);
insert into cities(province_id, name, id ) values (11, "El Tambo", 410);
insert into cities(province_id, name, id ) values (11, "Florencia", 411);
insert into cities(province_id, name, id ) values (11, "Guachené", 412);
insert into cities(province_id, name, id ) values (11, "Guapi", 413);
insert into cities(province_id, name, id ) values (11, "Inzá", 414);
insert into cities(province_id, name, id ) values (11, "Jambaló", 415);
insert into cities(province_id, name, id ) values (11, "La Sierra", 416);
insert into cities(province_id, name, id ) values (11, "La Vega", 417);
insert into cities(province_id, name, id ) values (11, "López", 418);
insert into cities(province_id, name, id ) values (11, "Mercaderes", 419);
insert into cities(province_id, name, id ) values (11, "Miranda", 420);
insert into cities(province_id, name, id ) values (11, "Morales", 421);
insert into cities(province_id, name, id ) values (11, "Padilla", 422);
insert into cities(province_id, name, id ) values (11, "Patía", 423);
insert into cities(province_id, name, id ) values (11, "Piamonte", 424);
insert into cities(province_id, name, id ) values (11, "Piendamó", 425);
insert into cities(province_id, name, id ) values (11, "Puerto Tejada", 426);
insert into cities(province_id, name, id ) values (11, "Puracé", 427);
insert into cities(province_id, name, id ) values (11, "Rosas", 428);
insert into cities(province_id, name, id ) values (11, "Santa Rosa", 429);
insert into cities(province_id, name, id ) values (11, "Silvia", 430);
insert into cities(province_id, name, id ) values (11, "Sotara", 431);
insert into cities(province_id, name, id ) values (11, "Suárez", 432);
insert into cities(province_id, name, id ) values (11, "Sucre", 433);
insert into cities(province_id, name, id ) values (11, "Timbío", 434);
insert into cities(province_id, name, id ) values (11, "Timbiquí", 435);
insert into cities(province_id, name, id ) values (11, "Toribio", 436);
insert into cities(province_id, name, id ) values (11, "Totoró", 437);
insert into cities(province_id, name, id ) values (11, "Villa Rica", 438);
insert into cities(province_id, name, id ) values (11, "Santander de Quilichao", 439);
insert into cities(province_id, name, id ) values (11, "San Sebastián", 440);
insert into cities(province_id, name, id ) values (11, "Páez", 441);
insert into cities(province_id, name, id ) values (12, "Valledupar", 442);
insert into cities(province_id, name, id ) values (12, "Aguachica", 443);
insert into cities(province_id, name, id ) values (12, "Agustín Codazzi", 444);
insert into cities(province_id, name, id ) values (12, "Astrea", 445);
insert into cities(province_id, name, id ) values (12, "Becerril", 446);
insert into cities(province_id, name, id ) values (12, "Bosconia", 447);
insert into cities(province_id, name, id ) values (12, "Chimichagua", 448);
insert into cities(province_id, name, id ) values (12, "Chiriguaná", 449);
insert into cities(province_id, name, id ) values (12, "Curumaní", 450);
insert into cities(province_id, name, id ) values (12, "El Copey", 451);
insert into cities(province_id, name, id ) values (12, "El Paso", 452);
insert into cities(province_id, name, id ) values (12, "Gamarra", 453);
insert into cities(province_id, name, id ) values (12, "González", 454);
insert into cities(province_id, name, id ) values (12, "La Gloria", 455);
insert into cities(province_id, name, id ) values (12, "Manaure", 456);
insert into cities(province_id, name, id ) values (12, "Pailitas", 457);
insert into cities(province_id, name, id ) values (12, "Pelaya", 458);
insert into cities(province_id, name, id ) values (12, "Pueblo Bello", 459);
insert into cities(province_id, name, id ) values (12, "La Paz", 460);
insert into cities(province_id, name, id ) values (12, "San Alberto", 461);
insert into cities(province_id, name, id ) values (12, "San Diego", 462);
insert into cities(province_id, name, id ) values (12, "San Martín", 463);
insert into cities(province_id, name, id ) values (12, "Tamalameque", 464);
insert into cities(province_id, name, id ) values (12, "Río de Oro", 465);
insert into cities(province_id, name, id ) values (12, "La Jagua de Ibirico", 466);
insert into cities(province_id, name, id ) values (13, "Istmina", 467);
insert into cities(province_id, name, id ) values (13, "Quibdó", 468);
insert into cities(province_id, name, id ) values (13, "Acandí", 469);
insert into cities(province_id, name, id ) values (13, "Alto Baudo", 470);
insert into cities(province_id, name, id ) values (13, "Atrato", 471);
insert into cities(province_id, name, id ) values (13, "Bagadó", 472);
insert into cities(province_id, name, id ) values (13, "Bahía Solano", 473);
insert into cities(province_id, name, id ) values (13, "Bajo Baudó", 474);
insert into cities(province_id, name, id ) values (13, "Bojaya", 475);
insert into cities(province_id, name, id ) values (13, "Cértegui", 476);
insert into cities(province_id, name, id ) values (13, "Condoto", 477);
insert into cities(province_id, name, id ) values (13, "Juradó", 478);
insert into cities(province_id, name, id ) values (13, "Lloró", 479);
insert into cities(province_id, name, id ) values (13, "Medio Atrato", 480);
insert into cities(province_id, name, id ) values (13, "Medio Baudó", 481);
insert into cities(province_id, name, id ) values (13, "Medio San Juan", 482);
insert into cities(province_id, name, id ) values (13, "Nóvita", 483);
insert into cities(province_id, name, id ) values (13, "Nuquí", 484);
insert into cities(province_id, name, id ) values (13, "Río Iro", 485);
insert into cities(province_id, name, id ) values (13, "Río Quito", 486);
insert into cities(province_id, name, id ) values (13, "Riosucio", 487);
insert into cities(province_id, name, id ) values (13, "Sipí", 488);
insert into cities(province_id, name, id ) values (13, "Unguía", 489);
insert into cities(province_id, name, id ) values (13, "El Litoral del San Juan", 490);
insert into cities(province_id, name, id ) values (13, "El Cantón del San Pablo", 491);
insert into cities(province_id, name, id ) values (13, "El Carmen de Atrato", 492);
insert into cities(province_id, name, id ) values (13, "San José del Palmar", 493);
insert into cities(province_id, name, id ) values (13, "Belén de Bajira", 494);
insert into cities(province_id, name, id ) values (13, "Carmen del Darien", 495);
insert into cities(province_id, name, id ) values (13, "Tadó", 496);
insert into cities(province_id, name, id ) values (13, "Unión Panamericana", 497);
insert into cities(province_id, name, id ) values (14, "San Bernardo del Viento", 498);
insert into cities(province_id, name, id ) values (14, "Montería", 499);
insert into cities(province_id, name, id ) values (14, "Ayapel", 500);
insert into cities(province_id, name, id ) values (14, "Buenavista", 501);
insert into cities(province_id, name, id ) values (14, "Canalete", 502);
insert into cities(province_id, name, id ) values (14, "Cereté", 503);
insert into cities(province_id, name, id ) values (14, "Chimá", 504);
insert into cities(province_id, name, id ) values (14, "Chinú", 505);
insert into cities(province_id, name, id ) values (14, "Cotorra", 506);
insert into cities(province_id, name, id ) values (14, "Lorica", 507);
insert into cities(province_id, name, id ) values (14, "Los Córdobas", 508);
insert into cities(province_id, name, id ) values (14, "Momil", 509);
insert into cities(province_id, name, id ) values (14, "Moñitos", 510);
insert into cities(province_id, name, id ) values (14, "Planeta Rica", 511);
insert into cities(province_id, name, id ) values (14, "Pueblo Nuevo", 512);
insert into cities(province_id, name, id ) values (14, "Puerto Escondido", 513);
insert into cities(province_id, name, id ) values (14, "Purísima", 514);
insert into cities(province_id, name, id ) values (14, "Sahagún", 515);
insert into cities(province_id, name, id ) values (14, "San Andrés Sotavento", 516);
insert into cities(province_id, name, id ) values (14, "San Antero", 517);
insert into cities(province_id, name, id ) values (14, "San Pelayo", 518);
insert into cities(province_id, name, id ) values (14, "Tierralta", 519);
insert into cities(province_id, name, id ) values (14, "Tuchín", 520);
insert into cities(province_id, name, id ) values (14, "Valencia", 521);
insert into cities(province_id, name, id ) values (14, "San José de Uré", 522);
insert into cities(province_id, name, id ) values (14, "Ciénaga de Oro", 523);
insert into cities(province_id, name, id ) values (14, "San Carlos", 524);
insert into cities(province_id, name, id ) values (14, "Montelíbano", 525);
insert into cities(province_id, name, id ) values (14, "La Apartada", 526);
insert into cities(province_id, name, id ) values (14, "Puerto Libertador", 527);
insert into cities(province_id, name, id ) values (15, "Anapoima", 528);
insert into cities(province_id, name, id ) values (15, "Arbeláez", 529);
insert into cities(province_id, name, id ) values (15, "Beltrán", 530);
insert into cities(province_id, name, id ) values (15, "Bituima", 531);
insert into cities(province_id, name, id ) values (15, "Bogotá D.C.", 532);
insert into cities(province_id, name, id ) values (15, "Bojacá", 533);
insert into cities(province_id, name, id ) values (15, "Cabrera", 534);
insert into cities(province_id, name, id ) values (15, "Cachipay", 535);
insert into cities(province_id, name, id ) values (15, "Cajicá", 536);
insert into cities(province_id, name, id ) values (15, "Caparrapí", 537);
insert into cities(province_id, name, id ) values (15, "Caqueza", 538);
insert into cities(province_id, name, id ) values (15, "Chaguaní", 539);
insert into cities(province_id, name, id ) values (15, "Chipaque", 540);
insert into cities(province_id, name, id ) values (15, "Choachí", 541);
insert into cities(province_id, name, id ) values (15, "Chocontá", 542);
insert into cities(province_id, name, id ) values (15, "Cogua", 543);
insert into cities(province_id, name, id ) values (15, "Cota", 544);
insert into cities(province_id, name, id ) values (15, "Cucunubá", 545);
insert into cities(province_id, name, id ) values (15, "El Colegio", 546);
insert into cities(province_id, name, id ) values (15, "El Rosal", 547);
insert into cities(province_id, name, id ) values (15, "Fomeque", 548);
insert into cities(province_id, name, id ) values (15, "Fosca", 549);
insert into cities(province_id, name, id ) values (15, "Funza", 550);
insert into cities(province_id, name, id ) values (15, "Fúquene", 551);
insert into cities(province_id, name, id ) values (15, "Gachala", 552);
insert into cities(province_id, name, id ) values (15, "Gachancipá", 553);
insert into cities(province_id, name, id ) values (15, "Gachetá", 554);
insert into cities(province_id, name, id ) values (15, "Girardot", 555);
insert into cities(province_id, name, id ) values (15, "Granada", 556);
insert into cities(province_id, name, id ) values (15, "Guachetá", 557);
insert into cities(province_id, name, id ) values (15, "Guaduas", 558);
insert into cities(province_id, name, id ) values (15, "Guasca", 559);
insert into cities(province_id, name, id ) values (15, "Guataquí", 560);
insert into cities(province_id, name, id ) values (15, "Guatavita", 561);
insert into cities(province_id, name, id ) values (15, "Guayabetal", 562);
insert into cities(province_id, name, id ) values (15, "Gutiérrez", 563);
insert into cities(province_id, name, id ) values (15, "Jerusalén", 564);
insert into cities(province_id, name, id ) values (15, "Junín", 565);
insert into cities(province_id, name, id ) values (15, "La Calera", 566);
insert into cities(province_id, name, id ) values (15, "La Mesa", 567);
insert into cities(province_id, name, id ) values (15, "La Palma", 568);
insert into cities(province_id, name, id ) values (15, "La Peña", 569);
insert into cities(province_id, name, id ) values (15, "La Vega", 570);
insert into cities(province_id, name, id ) values (15, "Lenguazaque", 571);
insert into cities(province_id, name, id ) values (15, "Macheta", 572);
insert into cities(province_id, name, id ) values (15, "Madrid", 573);
insert into cities(province_id, name, id ) values (15, "Manta", 574);
insert into cities(province_id, name, id ) values (15, "Medina", 575);
insert into cities(province_id, name, id ) values (15, "Mosquera", 576);
insert into cities(province_id, name, id ) values (15, "Nariño", 577);
insert into cities(province_id, name, id ) values (15, "Nemocón", 578);
insert into cities(province_id, name, id ) values (15, "Nilo", 579);
insert into cities(province_id, name, id ) values (15, "Nimaima", 580);
insert into cities(province_id, name, id ) values (15, "Nocaima", 581);
insert into cities(province_id, name, id ) values (15, "Venecia", 582);
insert into cities(province_id, name, id ) values (15, "Pacho", 583);
insert into cities(province_id, name, id ) values (15, "Paime", 584);
insert into cities(province_id, name, id ) values (15, "Pandi", 585);
insert into cities(province_id, name, id ) values (15, "Paratebueno", 586);
insert into cities(province_id, name, id ) values (15, "Pasca", 587);
insert into cities(province_id, name, id ) values (15, "Puerto Salgar", 588);
insert into cities(province_id, name, id ) values (15, "Pulí", 589);
insert into cities(province_id, name, id ) values (15, "Quebradanegra", 590);
insert into cities(province_id, name, id ) values (15, "Quetame", 591);
insert into cities(province_id, name, id ) values (15, "Quipile", 592);
insert into cities(province_id, name, id ) values (15, "Apulo", 593);
insert into cities(province_id, name, id ) values (15, "Ricaurte", 594);
insert into cities(province_id, name, id ) values (15, "San Bernardo", 595);
insert into cities(province_id, name, id ) values (15, "San Cayetano", 596);
insert into cities(province_id, name, id ) values (15, "San Francisco", 597);
insert into cities(province_id, name, id ) values (15, "Sesquilé", 598);
insert into cities(province_id, name, id ) values (15, "Sibaté", 599);
insert into cities(province_id, name, id ) values (15, "Silvania", 600);
insert into cities(province_id, name, id ) values (15, "Simijaca", 601);
insert into cities(province_id, name, id ) values (15, "Soacha", 602);
insert into cities(province_id, name, id ) values (15, "Subachoque", 603);
insert into cities(province_id, name, id ) values (15, "Suesca", 604);
insert into cities(province_id, name, id ) values (15, "Supatá", 605);
insert into cities(province_id, name, id ) values (15, "Susa", 606);
insert into cities(province_id, name, id ) values (15, "Sutatausa", 607);
insert into cities(province_id, name, id ) values (15, "Tabio", 608);
insert into cities(province_id, name, id ) values (15, "Tausa", 609);
insert into cities(province_id, name, id ) values (15, "Tena", 610);
insert into cities(province_id, name, id ) values (15, "Tenjo", 611);
insert into cities(province_id, name, id ) values (15, "Tibacuy", 612);
insert into cities(province_id, name, id ) values (15, "Tibirita", 613);
insert into cities(province_id, name, id ) values (15, "Tocaima", 614);
insert into cities(province_id, name, id ) values (15, "Tocancipá", 615);
insert into cities(province_id, name, id ) values (15, "Topaipí", 616);
insert into cities(province_id, name, id ) values (15, "Ubalá", 617);
insert into cities(province_id, name, id ) values (15, "Ubaque", 618);
insert into cities(province_id, name, id ) values (15, "Une", 619);
insert into cities(province_id, name, id ) values (15, "Útica", 620);
insert into cities(province_id, name, id ) values (15, "Vianí", 621);
insert into cities(province_id, name, id ) values (15, "Villagómez", 622);
insert into cities(province_id, name, id ) values (15, "Villapinzón", 623);
insert into cities(province_id, name, id ) values (15, "Villeta", 624);
insert into cities(province_id, name, id ) values (15, "Viotá", 625);
insert into cities(province_id, name, id ) values (15, "Zipacón", 626);
insert into cities(province_id, name, id ) values (15, "San Juan de Río Seco", 627);
insert into cities(province_id, name, id ) values (15, "Villa de San Diego de Ubate", 628);
insert into cities(province_id, name, id ) values (15, "Guayabal de Siquima", 629);
insert into cities(province_id, name, id ) values (15, "San Antonio del Tequendama", 630);
insert into cities(province_id, name, id ) values (15, "Agua de Dios", 631);
insert into cities(province_id, name, id ) values (15, "Carmen de Carupa", 632);
insert into cities(province_id, name, id ) values (15, "Vergara", 633);
insert into cities(province_id, name, id ) values (15, "Albán", 634);
insert into cities(province_id, name, id ) values (15, "Anolaima", 635);
insert into cities(province_id, name, id ) values (15, "Chía", 636);
insert into cities(province_id, name, id ) values (15, "El Peñón", 637);
insert into cities(province_id, name, id ) values (15, "Sopó", 638);
insert into cities(province_id, name, id ) values (15, "Gama", 639);
insert into cities(province_id, name, id ) values (15, "Sasaima", 640);
insert into cities(province_id, name, id ) values (15, "Yacopí", 641);
insert into cities(province_id, name, id ) values (15, "Fusagasugá", 642);
insert into cities(province_id, name, id ) values (15, "Zipaquirá", 643);
insert into cities(province_id, name, id ) values (15, "Facatativá", 644);
insert into cities(province_id, name, id ) values (16, "Inírida", 645);
insert into cities(province_id, name, id ) values (16, "Barranco Minas", 646);
insert into cities(province_id, name, id ) values (16, "Mapiripana", 647);
insert into cities(province_id, name, id ) values (16, "San Felipe", 648);
insert into cities(province_id, name, id ) values (16, "Puerto Colombia", 649);
insert into cities(province_id, name, id ) values (16, "La Guadalupe", 650);
insert into cities(province_id, name, id ) values (16, "Cacahual", 651);
insert into cities(province_id, name, id ) values (16, "Pana Pana", 652);
insert into cities(province_id, name, id ) values (16, "Morichal", 653);
insert into cities(province_id, name, id ) values (17, "Calamar", 654);
insert into cities(province_id, name, id ) values (17, "San José del Guaviare", 655);
insert into cities(province_id, name, id ) values (17, "Miraflores", 656);
insert into cities(province_id, name, id ) values (17, "El Retorno", 657);
insert into cities(province_id, name, id ) values (18, "Neiva", 658);
insert into cities(province_id, name, id ) values (18, "Acevedo", 659);
insert into cities(province_id, name, id ) values (18, "Agrado", 660);
insert into cities(province_id, name, id ) values (18, "Aipe", 661);
insert into cities(province_id, name, id ) values (18, "Algeciras", 662);
insert into cities(province_id, name, id ) values (18, "Altamira", 663);
insert into cities(province_id, name, id ) values (18, "Baraya", 664);
insert into cities(province_id, name, id ) values (18, "Campoalegre", 665);
insert into cities(province_id, name, id ) values (18, "Colombia", 666);
insert into cities(province_id, name, id ) values (18, "Elías", 667);
insert into cities(province_id, name, id ) values (18, "Garzón", 668);
insert into cities(province_id, name, id ) values (18, "Gigante", 669);
insert into cities(province_id, name, id ) values (18, "Guadalupe", 670);
insert into cities(province_id, name, id ) values (18, "Hobo", 671);
insert into cities(province_id, name, id ) values (18, "Iquira", 672);
insert into cities(province_id, name, id ) values (18, "Isnos", 673);
insert into cities(province_id, name, id ) values (18, "La Argentina", 674);
insert into cities(province_id, name, id ) values (18, "La Plata", 675);
insert into cities(province_id, name, id ) values (18, "Nátaga", 676);
insert into cities(province_id, name, id ) values (18, "Oporapa", 677);
insert into cities(province_id, name, id ) values (18, "Paicol", 678);
insert into cities(province_id, name, id ) values (18, "Palermo", 679);
insert into cities(province_id, name, id ) values (18, "Palestina", 680);
insert into cities(province_id, name, id ) values (18, "Pital", 681);
insert into cities(province_id, name, id ) values (18, "Pitalito", 682);
insert into cities(province_id, name, id ) values (18, "Rivera", 683);
insert into cities(province_id, name, id ) values (18, "Saladoblanco", 684);
insert into cities(province_id, name, id ) values (18, "Santa María", 685);
insert into cities(province_id, name, id ) values (18, "Suaza", 686);
insert into cities(province_id, name, id ) values (18, "Tarqui", 687);
insert into cities(province_id, name, id ) values (18, "Tesalia", 688);
insert into cities(province_id, name, id ) values (18, "Tello", 689);
insert into cities(province_id, name, id ) values (18, "Teruel", 690);
insert into cities(province_id, name, id ) values (18, "Timaná", 691);
insert into cities(province_id, name, id ) values (18, "Villavieja", 692);
insert into cities(province_id, name, id ) values (18, "Yaguará", 693);
insert into cities(province_id, name, id ) values (18, "San Agustín", 694);
insert into cities(province_id, name, id ) values (19, "Riohacha", 695);
insert into cities(province_id, name, id ) values (19, "Albania", 696);
insert into cities(province_id, name, id ) values (19, "Barrancas", 697);
insert into cities(province_id, name, id ) values (19, "Dibula", 698);
insert into cities(province_id, name, id ) values (19, "Distracción", 699);
insert into cities(province_id, name, id ) values (19, "El Molino", 700);
insert into cities(province_id, name, id ) values (19, "Fonseca", 701);
insert into cities(province_id, name, id ) values (19, "Hatonuevo", 702);
insert into cities(province_id, name, id ) values (19, "Maicao", 703);
insert into cities(province_id, name, id ) values (19, "Manaure", 704);
insert into cities(province_id, name, id ) values (19, "Uribia", 705);
insert into cities(province_id, name, id ) values (19, "Urumita", 706);
insert into cities(province_id, name, id ) values (19, "Villanueva", 707);
insert into cities(province_id, name, id ) values (19, "La Jagua del Pilar", 708);
insert into cities(province_id, name, id ) values (19, "San Juan del Cesar", 709);
insert into cities(province_id, name, id ) values (20, "Santa Marta", 710);
insert into cities(province_id, name, id ) values (20, "Algarrobo", 711);
insert into cities(province_id, name, id ) values (20, "Aracataca", 712);
insert into cities(province_id, name, id ) values (20, "Ariguaní", 713);
insert into cities(province_id, name, id ) values (20, "Cerro San Antonio", 714);
insert into cities(province_id, name, id ) values (20, "Chivolo", 715);
insert into cities(province_id, name, id ) values (20, "Concordia", 716);
insert into cities(province_id, name, id ) values (20, "El Banco", 717);
insert into cities(province_id, name, id ) values (20, "El Piñon", 718);
insert into cities(province_id, name, id ) values (20, "El Retén", 719);
insert into cities(province_id, name, id ) values (20, "Fundación", 720);
insert into cities(province_id, name, id ) values (20, "Guamal", 721);
insert into cities(province_id, name, id ) values (20, "Nueva Granada", 722);
insert into cities(province_id, name, id ) values (20, "Pedraza", 723);
insert into cities(province_id, name, id ) values (20, "Pivijay", 724);
insert into cities(province_id, name, id ) values (20, "Plato", 725);
insert into cities(province_id, name, id ) values (20, "Remolino", 726);
insert into cities(province_id, name, id ) values (20, "Salamina", 727);
insert into cities(province_id, name, id ) values (20, "San Zenón", 728);
insert into cities(province_id, name, id ) values (20, "Santa Ana", 729);
insert into cities(province_id, name, id ) values (20, "Sitionuevo", 730);
insert into cities(province_id, name, id ) values (20, "Tenerife", 731);
insert into cities(province_id, name, id ) values (20, "Zapayán", 732);
insert into cities(province_id, name, id ) values (20, "Zona Bananera", 733);
insert into cities(province_id, name, id ) values (20, "San Sebastián de Buenavista", 734);
insert into cities(province_id, name, id ) values (20, "Sabanas de San Angel", 735);
insert into cities(province_id, name, id ) values (20, "Pijiño del Carmen", 736);
insert into cities(province_id, name, id ) values (20, "Santa Bárbara de Pinto", 737);
insert into cities(province_id, name, id ) values (20, "Pueblo Viejo", 738);
insert into cities(province_id, name, id ) values (20, "Ciénaga", 739);
insert into cities(province_id, name, id ) values (21, "Villavicencio", 740);
insert into cities(province_id, name, id ) values (21, "Acacias", 741);
insert into cities(province_id, name, id ) values (21, "Cabuyaro", 742);
insert into cities(province_id, name, id ) values (21, "Cubarral", 743);
insert into cities(province_id, name, id ) values (21, "Cumaral", 744);
insert into cities(province_id, name, id ) values (21, "El Calvario", 745);
insert into cities(province_id, name, id ) values (21, "El Castillo", 746);
insert into cities(province_id, name, id ) values (21, "El Dorado", 747);
insert into cities(province_id, name, id ) values (21, "Granada", 748);
insert into cities(province_id, name, id ) values (21, "Guamal", 749);
insert into cities(province_id, name, id ) values (21, "Mapiripán", 750);
insert into cities(province_id, name, id ) values (21, "Mesetas", 751);
insert into cities(province_id, name, id ) values (21, "La Macarena", 752);
insert into cities(province_id, name, id ) values (21, "Uribe", 753);
insert into cities(province_id, name, id ) values (21, "Lejanías", 754);
insert into cities(province_id, name, id ) values (21, "Puerto Concordia", 755);
insert into cities(province_id, name, id ) values (21, "Puerto Gaitán", 756);
insert into cities(province_id, name, id ) values (21, "Puerto López", 757);
insert into cities(province_id, name, id ) values (21, "Puerto Lleras", 758);
insert into cities(province_id, name, id ) values (21, "Puerto Rico", 759);
insert into cities(province_id, name, id ) values (21, "Restrepo", 760);
insert into cities(province_id, name, id ) values (21, "San Juanito", 761);
insert into cities(province_id, name, id ) values (21, "San Martín", 762);
insert into cities(province_id, name, id ) values (21, "Vista Hermosa", 763);
insert into cities(province_id, name, id ) values (21, "Barranca de Upía", 764);
insert into cities(province_id, name, id ) values (21, "Fuente de Oro", 765);
insert into cities(province_id, name, id ) values (21, "San Carlos de Guaroa", 766);
insert into cities(province_id, name, id ) values (21, "San Juan de Arama", 767);
insert into cities(province_id, name, id ) values (21, "Castilla la Nueva", 768);
insert into cities(province_id, name, id ) values (22, "Santacruz", 769);
insert into cities(province_id, name, id ) values (22, "Pasto", 770);
insert into cities(province_id, name, id ) values (22, "Albán", 771);
insert into cities(province_id, name, id ) values (22, "Aldana", 772);
insert into cities(province_id, name, id ) values (22, "Ancuyá", 773);
insert into cities(province_id, name, id ) values (22, "Barbacoas", 774);
insert into cities(province_id, name, id ) values (22, "Colón", 775);
insert into cities(province_id, name, id ) values (22, "Consaca", 776);
insert into cities(province_id, name, id ) values (22, "Contadero", 777);
insert into cities(province_id, name, id ) values (22, "Córdoba", 778);
insert into cities(province_id, name, id ) values (22, "Cuaspud", 779);
insert into cities(province_id, name, id ) values (22, "Cumbal", 780);
insert into cities(province_id, name, id ) values (22, "Cumbitara", 781);
insert into cities(province_id, name, id ) values (22, "El Charco", 782);
insert into cities(province_id, name, id ) values (22, "El Peñol", 783);
insert into cities(province_id, name, id ) values (22, "El Rosario", 784);
insert into cities(province_id, name, id ) values (22, "El Tambo", 785);
insert into cities(province_id, name, id ) values (22, "Funes", 786);
insert into cities(province_id, name, id ) values (22, "Guachucal", 787);
insert into cities(province_id, name, id ) values (22, "Guaitarilla", 788);
insert into cities(province_id, name, id ) values (22, "Gualmatán", 789);
insert into cities(province_id, name, id ) values (22, "Iles", 790);
insert into cities(province_id, name, id ) values (22, "Imués", 791);
insert into cities(province_id, name, id ) values (22, "Ipiales", 792);
insert into cities(province_id, name, id ) values (22, "La Cruz", 793);
insert into cities(province_id, name, id ) values (22, "La Florida", 794);
insert into cities(province_id, name, id ) values (22, "La Llanada", 795);
insert into cities(province_id, name, id ) values (22, "La Tola", 796);
insert into cities(province_id, name, id ) values (22, "La Unión", 797);
insert into cities(province_id, name, id ) values (22, "Leiva", 798);
insert into cities(province_id, name, id ) values (22, "Linares", 799);
insert into cities(province_id, name, id ) values (22, "Los Andes", 800);
insert into cities(province_id, name, id ) values (22, "Magüí", 801);
insert into cities(province_id, name, id ) values (22, "Mallama", 802);
insert into cities(province_id, name, id ) values (22, "Mosquera", 803);
insert into cities(province_id, name, id ) values (22, "Nariño", 804);
insert into cities(province_id, name, id ) values (22, "Olaya Herrera", 805);
insert into cities(province_id, name, id ) values (22, "Ospina", 806);
insert into cities(province_id, name, id ) values (22, "Francisco Pizarro", 807);
insert into cities(province_id, name, id ) values (22, "Policarpa", 808);
insert into cities(province_id, name, id ) values (22, "Potosí", 809);
insert into cities(province_id, name, id ) values (22, "Providencia", 810);
insert into cities(province_id, name, id ) values (22, "Puerres", 811);
insert into cities(province_id, name, id ) values (22, "Pupiales", 812);
insert into cities(province_id, name, id ) values (22, "Ricaurte", 813);
insert into cities(province_id, name, id ) values (22, "Roberto Payán", 814);
insert into cities(province_id, name, id ) values (22, "Samaniego", 815);
insert into cities(province_id, name, id ) values (22, "Sandoná", 816);
insert into cities(province_id, name, id ) values (22, "San Bernardo", 817);
insert into cities(province_id, name, id ) values (22, "San Lorenzo", 818);
insert into cities(province_id, name, id ) values (22, "San Pablo", 819);
insert into cities(province_id, name, id ) values (22, "Santa Bárbara", 820);
insert into cities(province_id, name, id ) values (22, "Sapuyes", 821);
insert into cities(province_id, name, id ) values (22, "Taminango", 822);
insert into cities(province_id, name, id ) values (22, "Tangua", 823);
insert into cities(province_id, name, id ) values (22, "Túquerres", 824);
insert into cities(province_id, name, id ) values (22, "Yacuanquer", 825);
insert into cities(province_id, name, id ) values (22, "San Pedro de Cartago", 826);
insert into cities(province_id, name, id ) values (22, "El Tablón de Gómez", 827);
insert into cities(province_id, name, id ) values (22, "Buesaco", 828);
insert into cities(province_id, name, id ) values (22, "San Andrés de Tumaco", 829);
insert into cities(province_id, name, id ) values (22, "Belén", 830);
insert into cities(province_id, name, id ) values (22, "Chachagüí", 831);
insert into cities(province_id, name, id ) values (22, "Arboleda", 832);
insert into cities(province_id, name, id ) values (23, "Silos", 833);
insert into cities(province_id, name, id ) values (23, "Cácota", 834);
insert into cities(province_id, name, id ) values (23, "Toledo", 835);
insert into cities(province_id, name, id ) values (23, "Mutiscua", 836);
insert into cities(province_id, name, id ) values (23, "El Zulia", 837);
insert into cities(province_id, name, id ) values (23, "Salazar", 838);
insert into cities(province_id, name, id ) values (23, "Cucutilla", 839);
insert into cities(province_id, name, id ) values (23, "Puerto Santander", 840);
insert into cities(province_id, name, id ) values (23, "Gramalote", 841);
insert into cities(province_id, name, id ) values (23, "El Tarra", 842);
insert into cities(province_id, name, id ) values (23, "Teorama", 843);
insert into cities(province_id, name, id ) values (23, "Arboledas", 844);
insert into cities(province_id, name, id ) values (23, "Lourdes", 845);
insert into cities(province_id, name, id ) values (23, "Bochalema", 846);
insert into cities(province_id, name, id ) values (23, "Convención", 847);
insert into cities(province_id, name, id ) values (23, "Hacarí", 848);
insert into cities(province_id, name, id ) values (23, "Herrán", 849);
insert into cities(province_id, name, id ) values (23, "Tibú", 850);
insert into cities(province_id, name, id ) values (23, "San Cayetano", 851);
insert into cities(province_id, name, id ) values (23, "San Calixto", 852);
insert into cities(province_id, name, id ) values (23, "La Playa", 853);
insert into cities(province_id, name, id ) values (23, "Chinácota", 854);
insert into cities(province_id, name, id ) values (23, "Ragonvalia", 855);
insert into cities(province_id, name, id ) values (23, "La Esperanza", 856);
insert into cities(province_id, name, id ) values (23, "Villa del Rosario", 857);
insert into cities(province_id, name, id ) values (23, "Chitagá", 858);
insert into cities(province_id, name, id ) values (23, "Sardinata", 859);
insert into cities(province_id, name, id ) values (23, "Abrego", 860);
insert into cities(province_id, name, id ) values (23, "Los Patios", 861);
insert into cities(province_id, name, id ) values (23, "Ocaña", 862);
insert into cities(province_id, name, id ) values (23, "Bucarasica", 863);
insert into cities(province_id, name, id ) values (23, "Santiago", 864);
insert into cities(province_id, name, id ) values (23, "Labateca", 865);
insert into cities(province_id, name, id ) values (23, "Cachirá", 866);
insert into cities(province_id, name, id ) values (23, "Villa Caro", 867);
insert into cities(province_id, name, id ) values (23, "Durania", 868);
insert into cities(province_id, name, id ) values (23, "Pamplona", 869);
insert into cities(province_id, name, id ) values (23, "Pamplonita", 870);
insert into cities(province_id, name, id ) values (23, "Cúcuta", 871);
insert into cities(province_id, name, id ) values (23, "El Carmen", 872);
insert into cities(province_id, name, id ) values (24, "Mocoa", 873);
insert into cities(province_id, name, id ) values (24, "Colón", 874);
insert into cities(province_id, name, id ) values (24, "Orito", 875);
insert into cities(province_id, name, id ) values (24, "Puerto Caicedo", 876);
insert into cities(province_id, name, id ) values (24, "Puerto Guzmán", 877);
insert into cities(province_id, name, id ) values (24, "Leguízamo", 878);
insert into cities(province_id, name, id ) values (24, "Sibundoy", 879);
insert into cities(province_id, name, id ) values (24, "San Francisco", 880);
insert into cities(province_id, name, id ) values (24, "San Miguel", 881);
insert into cities(province_id, name, id ) values (24, "Santiago", 882);
insert into cities(province_id, name, id ) values (24, "Valle de Guamez", 883);
insert into cities(province_id, name, id ) values (24, "Puerto Asís", 884);
insert into cities(province_id, name, id ) values (24, "Villagarzón", 885);
insert into cities(province_id, name, id ) values (25, "Armenia", 886);
insert into cities(province_id, name, id ) values (25, "Buenavista", 887);
insert into cities(province_id, name, id ) values (25, "Circasia", 888);
insert into cities(province_id, name, id ) values (25, "Córdoba", 889);
insert into cities(province_id, name, id ) values (25, "Filandia", 890);
insert into cities(province_id, name, id ) values (25, "La Tebaida", 891);
insert into cities(province_id, name, id ) values (25, "Montenegro", 892);
insert into cities(province_id, name, id ) values (25, "Pijao", 893);
insert into cities(province_id, name, id ) values (25, "Quimbaya", 894);
insert into cities(province_id, name, id ) values (25, "Salento", 895);
insert into cities(province_id, name, id ) values (25, "Calarcá", 896);
insert into cities(province_id, name, id ) values (25, "Génova", 897);
insert into cities(province_id, name, id ) values (26, "Pereira", 898);
insert into cities(province_id, name, id ) values (26, "Apía", 899);
insert into cities(province_id, name, id ) values (26, "Balboa", 900);
insert into cities(province_id, name, id ) values (26, "Dosquebradas", 901);
insert into cities(province_id, name, id ) values (26, "Guática", 902);
insert into cities(province_id, name, id ) values (26, "La Celia", 903);
insert into cities(province_id, name, id ) values (26, "La Virginia", 904);
insert into cities(province_id, name, id ) values (26, "Marsella", 905);
insert into cities(province_id, name, id ) values (26, "Mistrató", 906);
insert into cities(province_id, name, id ) values (26, "Pueblo Rico", 907);
insert into cities(province_id, name, id ) values (26, "Quinchía", 908);
insert into cities(province_id, name, id ) values (26, "Santuario", 909);
insert into cities(province_id, name, id ) values (26, "Santa Rosa de Cabal", 910);
insert into cities(province_id, name, id ) values (26, "Belén de Umbría", 911);
insert into cities(province_id, name, id ) values (27, "Puerto Wilches", 912);
insert into cities(province_id, name, id ) values (27, "Puerto Parra", 913);
insert into cities(province_id, name, id ) values (27, "Bucaramanga", 914);
insert into cities(province_id, name, id ) values (27, "Aguada", 915);
insert into cities(province_id, name, id ) values (27, "Albania", 916);
insert into cities(province_id, name, id ) values (27, "Aratoca", 917);
insert into cities(province_id, name, id ) values (27, "Barbosa", 918);
insert into cities(province_id, name, id ) values (27, "Barichara", 919);
insert into cities(province_id, name, id ) values (27, "Barrancabermeja", 920);
insert into cities(province_id, name, id ) values (27, "Betulia", 921);
insert into cities(province_id, name, id ) values (27, "Bolívar", 922);
insert into cities(province_id, name, id ) values (27, "Cabrera", 923);
insert into cities(province_id, name, id ) values (27, "California", 924);
insert into cities(province_id, name, id ) values (27, "Carcasí", 925);
insert into cities(province_id, name, id ) values (27, "Cepitá", 926);
insert into cities(province_id, name, id ) values (27, "Cerrito", 927);
insert into cities(province_id, name, id ) values (27, "Charalá", 928);
insert into cities(province_id, name, id ) values (27, "Charta", 929);
insert into cities(province_id, name, id ) values (27, "Chipatá", 930);
insert into cities(province_id, name, id ) values (27, "Cimitarra", 931);
insert into cities(province_id, name, id ) values (27, "Concepción", 932);
insert into cities(province_id, name, id ) values (27, "Confines", 933);
insert into cities(province_id, name, id ) values (27, "Contratación", 934);
insert into cities(province_id, name, id ) values (27, "Coromoro", 935);
insert into cities(province_id, name, id ) values (27, "Curití", 936);
insert into cities(province_id, name, id ) values (27, "El Guacamayo", 937);
insert into cities(province_id, name, id ) values (27, "El Playón", 938);
insert into cities(province_id, name, id ) values (27, "Encino", 939);
insert into cities(province_id, name, id ) values (27, "Enciso", 940);
insert into cities(province_id, name, id ) values (27, "Florián", 941);
insert into cities(province_id, name, id ) values (27, "Floridablanca", 942);
insert into cities(province_id, name, id ) values (27, "Galán", 943);
insert into cities(province_id, name, id ) values (27, "Gambita", 944);
insert into cities(province_id, name, id ) values (27, "Girón", 945);
insert into cities(province_id, name, id ) values (27, "Guaca", 946);
insert into cities(province_id, name, id ) values (27, "Guadalupe", 947);
insert into cities(province_id, name, id ) values (27, "Guapotá", 948);
insert into cities(province_id, name, id ) values (27, "Guavatá", 949);
insert into cities(province_id, name, id ) values (27, "Güepsa", 950);
insert into cities(province_id, name, id ) values (27, "Jesús María", 951);
insert into cities(province_id, name, id ) values (27, "Jordán", 952);
insert into cities(province_id, name, id ) values (27, "La Belleza", 953);
insert into cities(province_id, name, id ) values (27, "Landázuri", 954);
insert into cities(province_id, name, id ) values (27, "La Paz", 955);
insert into cities(province_id, name, id ) values (27, "Lebríja", 956);
insert into cities(province_id, name, id ) values (27, "Los Santos", 957);
insert into cities(province_id, name, id ) values (27, "Macaravita", 958);
insert into cities(province_id, name, id ) values (27, "Málaga", 959);
insert into cities(province_id, name, id ) values (27, "Matanza", 960);
insert into cities(province_id, name, id ) values (27, "Mogotes", 961);
insert into cities(province_id, name, id ) values (27, "Molagavita", 962);
insert into cities(province_id, name, id ) values (27, "Ocamonte", 963);
insert into cities(province_id, name, id ) values (27, "Oiba", 964);
insert into cities(province_id, name, id ) values (27, "Onzaga", 965);
insert into cities(province_id, name, id ) values (27, "Palmar", 966);
insert into cities(province_id, name, id ) values (27, "Páramo", 967);
insert into cities(province_id, name, id ) values (27, "Piedecuesta", 968);
insert into cities(province_id, name, id ) values (27, "Pinchote", 969);
insert into cities(province_id, name, id ) values (27, "Puente Nacional", 970);
insert into cities(province_id, name, id ) values (27, "Rionegro", 971);
insert into cities(province_id, name, id ) values (27, "San Andrés", 972);
insert into cities(province_id, name, id ) values (27, "San Gil", 973);
insert into cities(province_id, name, id ) values (27, "San Joaquín", 974);
insert into cities(province_id, name, id ) values (27, "San Miguel", 975);
insert into cities(province_id, name, id ) values (27, "Santa Bárbara", 976);
insert into cities(province_id, name, id ) values (27, "Simacota", 977);
insert into cities(province_id, name, id ) values (27, "Socorro", 978);
insert into cities(province_id, name, id ) values (27, "Suaita", 979);
insert into cities(province_id, name, id ) values (27, "Sucre", 980);
insert into cities(province_id, name, id ) values (27, "Suratá", 981);
insert into cities(province_id, name, id ) values (27, "Tona", 982);
insert into cities(province_id, name, id ) values (27, "Vélez", 983);
insert into cities(province_id, name, id ) values (27, "Vetas", 984);
insert into cities(province_id, name, id ) values (27, "Villanueva", 985);
insert into cities(province_id, name, id ) values (27, "Zapatoca", 986);
insert into cities(province_id, name, id ) values (27, "Palmas del Socorro", 987);
insert into cities(province_id, name, id ) values (27, "San Vicente de Chucurí", 988);
insert into cities(province_id, name, id ) values (27, "San José de Miranda", 989);
insert into cities(province_id, name, id ) values (27, "Santa Helena del Opón", 990);
insert into cities(province_id, name, id ) values (27, "Sabana de Torres", 991);
insert into cities(province_id, name, id ) values (27, "El Carmen de Chucurí", 992);
insert into cities(province_id, name, id ) values (27, "Valle de San José", 993);
insert into cities(province_id, name, id ) values (27, "San Benito", 994);
insert into cities(province_id, name, id ) values (27, "Hato", 995);
insert into cities(province_id, name, id ) values (27, "Chimá", 996);
insert into cities(province_id, name, id ) values (27, "Capitanejo", 997);
insert into cities(province_id, name, id ) values (27, "El Peñón", 998);
insert into cities(province_id, name, id ) values (28, "Sincelejo", 999);
insert into cities(province_id, name, id ) values (28, "Buenavista", 1000);
insert into cities(province_id, name, id ) values (28, "Caimito", 1001);
insert into cities(province_id, name, id ) values (28, "Coloso", 1002);
insert into cities(province_id, name, id ) values (28, "Coveñas", 1003);
insert into cities(province_id, name, id ) values (28, "Chalán", 1004);
insert into cities(province_id, name, id ) values (28, "El Roble", 1005);
insert into cities(province_id, name, id ) values (28, "Galeras", 1006);
insert into cities(province_id, name, id ) values (28, "Guaranda", 1007);
insert into cities(province_id, name, id ) values (28, "La Unión", 1008);
insert into cities(province_id, name, id ) values (28, "Los Palmitos", 1009);
insert into cities(province_id, name, id ) values (28, "Majagual", 1010);
insert into cities(province_id, name, id ) values (28, "Morroa", 1011);
insert into cities(province_id, name, id ) values (28, "Ovejas", 1012);
insert into cities(province_id, name, id ) values (28, "Palmito", 1013);
insert into cities(province_id, name, id ) values (28, "San Benito Abad", 1014);
insert into cities(province_id, name, id ) values (28, "San Marcos", 1015);
insert into cities(province_id, name, id ) values (28, "San Onofre", 1016);
insert into cities(province_id, name, id ) values (28, "San Pedro", 1017);
insert into cities(province_id, name, id ) values (28, "Sucre", 1018);
insert into cities(province_id, name, id ) values (28, "Tolú Viejo", 1019);
insert into cities(province_id, name, id ) values (28, "San Luis de Sincé", 1020);
insert into cities(province_id, name, id ) values (28, "San Juan de Betulia", 1021);
insert into cities(province_id, name, id ) values (28, "Santiago de Tolú", 1022);
insert into cities(province_id, name, id ) values (28, "Sampués", 1023);
insert into cities(province_id, name, id ) values (28, "Corozal", 1024);
insert into cities(province_id, name, id ) values (29, "Alpujarra", 1025);
insert into cities(province_id, name, id ) values (29, "Alvarado", 1026);
insert into cities(province_id, name, id ) values (29, "Ambalema", 1027);
insert into cities(province_id, name, id ) values (29, "Armero", 1028);
insert into cities(province_id, name, id ) values (29, "Ataco", 1029);
insert into cities(province_id, name, id ) values (29, "Cajamarca", 1030);
insert into cities(province_id, name, id ) values (29, "Chaparral", 1031);
insert into cities(province_id, name, id ) values (29, "Coello", 1032);
insert into cities(province_id, name, id ) values (29, "Coyaima", 1033);
insert into cities(province_id, name, id ) values (29, "Cunday", 1034);
insert into cities(province_id, name, id ) values (29, "Dolores", 1035);
insert into cities(province_id, name, id ) values (29, "Espinal", 1036);
insert into cities(province_id, name, id ) values (29, "Falan", 1037);
insert into cities(province_id, name, id ) values (29, "Flandes", 1038);
insert into cities(province_id, name, id ) values (29, "Fresno", 1039);
insert into cities(province_id, name, id ) values (29, "Guamo", 1040);
insert into cities(province_id, name, id ) values (29, "Herveo", 1041);
insert into cities(province_id, name, id ) values (29, "Honda", 1042);
insert into cities(province_id, name, id ) values (29, "Icononzo", 1043);
insert into cities(province_id, name, id ) values (29, "Mariquita", 1044);
insert into cities(province_id, name, id ) values (29, "Melgar", 1045);
insert into cities(province_id, name, id ) values (29, "Murillo", 1046);
insert into cities(province_id, name, id ) values (29, "Natagaima", 1047);
insert into cities(province_id, name, id ) values (29, "Ortega", 1048);
insert into cities(province_id, name, id ) values (29, "Palocabildo", 1049);
insert into cities(province_id, name, id ) values (29, "Piedras", 1050);
insert into cities(province_id, name, id ) values (29, "Planadas", 1051);
insert into cities(province_id, name, id ) values (29, "Prado", 1052);
insert into cities(province_id, name, id ) values (29, "Purificación", 1053);
insert into cities(province_id, name, id ) values (29, "Rio Blanco", 1054);
insert into cities(province_id, name, id ) values (29, "Roncesvalles", 1055);
insert into cities(province_id, name, id ) values (29, "Rovira", 1056);
insert into cities(province_id, name, id ) values (29, "Saldaña", 1057);
insert into cities(province_id, name, id ) values (29, "Santa Isabel", 1058);
insert into cities(province_id, name, id ) values (29, "Venadillo", 1059);
insert into cities(province_id, name, id ) values (29, "Villahermosa", 1060);
insert into cities(province_id, name, id ) values (29, "Villarrica", 1061);
insert into cities(province_id, name, id ) values (29, "Valle de San Juan", 1062);
insert into cities(province_id, name, id ) values (29, "Carmen de Apicala", 1063);
insert into cities(province_id, name, id ) values (29, "San Luis", 1064);
insert into cities(province_id, name, id ) values (29, "San Antonio", 1065);
insert into cities(province_id, name, id ) values (29, "Casabianca", 1066);
insert into cities(province_id, name, id ) values (29, "Anzoátegui", 1067);
insert into cities(province_id, name, id ) values (29, "Ibagué", 1068);
insert into cities(province_id, name, id ) values (29, "Líbano", 1069);
insert into cities(province_id, name, id ) values (29, "Lérida", 1070);
insert into cities(province_id, name, id ) values (29, "Suárez", 1071);
insert into cities(province_id, name, id ) values (30, "El Dovio", 1072);
insert into cities(province_id, name, id ) values (30, "Roldanillo", 1073);
insert into cities(province_id, name, id ) values (30, "Argelia", 1074);
insert into cities(province_id, name, id ) values (30, "Sevilla", 1075);
insert into cities(province_id, name, id ) values (30, "Zarzal", 1076);
insert into cities(province_id, name, id ) values (30, "El Cerrito", 1077);
insert into cities(province_id, name, id ) values (30, "Cartago", 1078);
insert into cities(province_id, name, id ) values (30, "Caicedonia", 1079);
insert into cities(province_id, name, id ) values (30, "El Cairo", 1080);
insert into cities(province_id, name, id ) values (30, "La Unión", 1081);
insert into cities(province_id, name, id ) values (30, "Restrepo", 1082);
insert into cities(province_id, name, id ) values (30, "Dagua", 1083);
insert into cities(province_id, name, id ) values (30, "Guacarí", 1084);
insert into cities(province_id, name, id ) values (30, "Ansermanuevo", 1085);
insert into cities(province_id, name, id ) values (30, "Bugalagrande", 1086);
insert into cities(province_id, name, id ) values (30, "La Victoria", 1087);
insert into cities(province_id, name, id ) values (30, "Ginebra", 1088);
insert into cities(province_id, name, id ) values (30, "Yumbo", 1089);
insert into cities(province_id, name, id ) values (30, "Obando", 1090);
insert into cities(province_id, name, id ) values (30, "Bolívar", 1091);
insert into cities(province_id, name, id ) values (30, "Cali", 1092);
insert into cities(province_id, name, id ) values (30, "San Pedro", 1093);
insert into cities(province_id, name, id ) values (30, "Guadalajara de Buga", 1094);
insert into cities(province_id, name, id ) values (30, "Calima", 1095);
insert into cities(province_id, name, id ) values (30, "Andalucía", 1096);
insert into cities(province_id, name, id ) values (30, "Pradera", 1097);
insert into cities(province_id, name, id ) values (30, "Yotoco", 1098);
insert into cities(province_id, name, id ) values (30, "Palmira", 1099);
insert into cities(province_id, name, id ) values (30, "Riofrío", 1100);
insert into cities(province_id, name, id ) values (30, "Alcalá", 1101);
insert into cities(province_id, name, id ) values (30, "Versalles", 1102);
insert into cities(province_id, name, id ) values (30, "El Águila", 1103);
insert into cities(province_id, name, id ) values (30, "Toro", 1104);
insert into cities(province_id, name, id ) values (30, "Candelaria", 1105);
insert into cities(province_id, name, id ) values (30, "La Cumbre", 1106);
insert into cities(province_id, name, id ) values (30, "Ulloa", 1107);
insert into cities(province_id, name, id ) values (30, "Trujillo", 1108);
insert into cities(province_id, name, id ) values (30, "Vijes", 1109);
insert into cities(province_id, name, id ) values (30, "Tuluá", 1110);
insert into cities(province_id, name, id ) values (30, "Florida", 1111);
insert into cities(province_id, name, id ) values (30, "Jamundí", 1112);
insert into cities(province_id, name, id ) values (30, "Buenaventura", 1113);
insert into cities(province_id, name, id ) values (31, "Mitú", 1114);
insert into cities(province_id, name, id ) values (31, "Caruru", 1115);
insert into cities(province_id, name, id ) values (31, "Pacoa", 1116);
insert into cities(province_id, name, id ) values (31, "Taraira", 1117);
insert into cities(province_id, name, id ) values (31, "Papunaua", 1118);
insert into cities(province_id, name, id ) values (31, "Yavaraté", 1119);
insert into cities(province_id, name, id ) values (32, "Puerto Carreño", 1120);
insert into cities(province_id, name, id ) values (32, "La Primavera", 1121);
insert into cities(province_id, name, id ) values (32, "Santa Rosalía", 1122);
insert into cities(province_id, name, id ) values (32, "Cumaribo", 1123);
