insert into provinces (id, name, country_id) values (1, "Amazonas", 1);
insert into provinces (id, name, country_id) values (2, "Antioquia", 1);
insert into provinces (id, name, country_id) values (3, "Arauca", 1);
insert into provinces (id, name, country_id) values (4, "Archipiélago de San Andrés", 1);
insert into provinces (id, name, country_id) values (5, "Atlántico", 1);
insert into provinces (id, name, country_id) values (6, "Bolívar", 1);
insert into provinces (id, name, country_id) values (7, "Boyacá", 1);
insert into provinces (id, name, country_id) values (8, "Caldas", 1);
insert into provinces (id, name, country_id) values (9, "Caquetá", 1);
insert into provinces (id, name, country_id) values (10, "Casanare", 1);
insert into provinces (id, name, country_id) values (11, "Cauca", 1);
insert into provinces (id, name, country_id) values (12, "Cesar", 1);
insert into provinces (id, name, country_id) values (13, "Chocó", 1);
insert into provinces (id, name, country_id) values (14, "Córdoba", 1);
insert into provinces (id, name, country_id) values (15, "Cundinamarca", 1);
insert into provinces (id, name, country_id) values (16, "Guainía", 1);
insert into provinces (id, name, country_id) values (17, "Guaviare", 1);
insert into provinces (id, name, country_id) values (18, "Huila", 1);
insert into provinces (id, name, country_id) values (19, "La Guajira", 1);
insert into provinces (id, name, country_id) values (20, "Magdalena", 1);
insert into provinces (id, name, country_id) values (21, "Meta", 1);
insert into provinces (id, name, country_id) values (22, "Nariño", 1);
insert into provinces (id, name, country_id) values (23, "Norte de Santander", 1);
insert into provinces (id, name, country_id) values (24, "Putumayo", 1);
insert into provinces (id, name, country_id) values (25, "Quindío", 1);
insert into provinces (id, name, country_id) values (26, "Risaralda", 1);
insert into provinces (id, name, country_id) values (27, "Santander", 1);
insert into provinces (id, name, country_id) values (28, "Sucre", 1);
insert into provinces (id, name, country_id) values (29, "Tolima", 1);
insert into provinces (id, name, country_id) values (30, "Valle del Cauca", 1);
insert into provinces (id, name, country_id) values (31, "Vaupés", 1);
insert into provinces (id, name, country_id) values (32, "Vichada", 1);
